import = [
  "~/.config/alacritty/catppuccin-frappe.toml"
]

[window]
decorations = "None"
startup_mode = "Maximized"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
normal = { family = "JetBrainsMono NF", style = "Regular" }
bold = { family = "JetBrainsMono NF", style = "Bold" }
italic = { family = "JetBrainsMono NF", style = "Italic" }
bold_italic = { family = "JetBrainsMono NF", style = "Bold Italic" }
size = 10.0

[scrolling]
history = 100000

[keyboard]
bindings = [
{key = "Escape", mods = "Alt", action = "ToggleViMode"},
{key = "i", mode = "Vi|~Search", action = "ToggleViMode"},
{key = "y", mode = "Vi", action = "Copy"},
]
